spring:
  datasource:
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: ${DRIVER_CLASS_NAME}
    url: ${URL}

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  jwt:
    secret: ${JWT_SECRET}


  mail:
    host: smtp.naver.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}  
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true